In [1]:
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
## 데이터 전처리

import pandas as pd
import numpy as np
import sys
import pickle

## 데이터 시각화
import seaborn as sb
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
## 딥러닝 모델링

from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from scipy.stats import skew, kurtosis
from xgboost import XGBClassifier
import joblib
import itertools
import missingno as msno
import os
import warnings
np.set_printoptions(threshold=sys.maxsize)
warnings.filterwarnings(action='ignore')

In [3]:
file_path = 'E:/중급/train_data.csv'
file_path2 = 'E:/중급/test_data.csv'
file_path3 = 'E:/중급/train_label.csv'
datapath = 'E:/중급/'

In [4]:
trn_df = pd.read_csv(file_path)
tst_df = pd.read_csv(file_path2)
lab_df = pd.read_csv(file_path3)
lab_df = lab_df['ID']

In [5]:
trn_df[trn_df['ID'] == 0]

      ID  sensor_A  sensor_B  sensor_C
0    0.0 -0.781257 -0.368624 -0.668834
1    0.0  0.152001 -1.032890  0.013465
2    0.0 -1.815408 -0.501477 -1.103025
3    0.0 -0.402909  2.288443 -0.792889
4    0.0 -1.109159  2.819857 -0.544780
..   ...       ...       ...       ...
126  0.0 -0.175901  0.694203 -0.784106
127  0.0  1.841955 -0.501477 -0.970187
128  0.0  0.757358 -0.501477 -0.660051
129  0.0  0.883474  0.694203 -1.962622
130  0.0  2.245526  0.561350 -0.598024

[131 rows x 4 columns]

In [6]:
dfmn = trn_df.groupby('ID').mean()

In [7]:
dfst = trn_df.groupby('ID').std()

In [8]:
dfmi = trn_df.groupby('ID').min()

In [9]:
dfma = trn_df.groupby('ID').max()

In [10]:
dfsk = trn_df.groupby('ID').skew() #왜도

In [11]:
trn_df = pd.concat([dfmn,dfst,dfmi,dfma,dfsk],axis=1)
trn_df

,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C
ID,,,,,,,,,,,,,,,
0.0,-0.062685,0.014724,-0.056515,0.988268,1.210087,0.980058,-1.815408,-2.627131,-2.768975,2.245526,2.952710,2.432525,0.521596,0.175776,-0.165921
1.0,-0.153611,0.014196,-0.078285,0.900904,0.973971,0.908227,-1.493521,-2.378179,-2.310316,1.911610,2.803103,2.155641,0.564537,0.326462,0.000843
2.0,0.051289,0.043324,-0.057817,1.036681,1.036154,1.088889,-1.752650,-2.369334,-3.462210,2.308284,2.413387,1.934155,0.295918,0.012605,-0.666971
3.0,0.063667,0.018329,-0.067171,0.893419,1.221790,1.083317,-1.581868,-3.308527,-2.258773,1.949018,2.616859,2.710428,0.249805,-0.296168,0.311712
4.0,-0.196459,-0.052498,-0.121069,0.948502,0.745984,1.043245,-1.786668,-2.697356,-2.426879,1.936368,2.025064,1.805276,0.506458,-0.258511,-0.092705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8955.0,0.070798,0.033142,-0.051450,1.081704,0.933349,0.939368,-2.127417,-2.238808,-2.182695,2.143425,2.134018,2.508128,-0.080680,-0.292391,0.279585
8956.0,0.030234,-0.018972,-0.109389,0.998156,0.909103,1.048331,-1.691912,-2.325185,-2.138404,1.907844,2.276148,1.986155,0.065697,0.040335,0.272105
8957.0,-0.147562,-0.013614,-0.003018,0.993478,1.099060,0.928519,-1.480673,-2.384529,-2.732372,1.921837,2.822242,1.643246,0.714042,0.062787,-0.796413
8958.0,0.137001,0.061176,-0.031824,1.041318,0.818964,1.050959,-1.519794,-1.637522,-2.859407,2.160748,3.012346,3.033175,0.379977,0.353045,0.324909
8959.0,-0.087678,-0.032589,-0.016548,0.972985,1.213935,1.129651,-1.654360,-3.351872,-2.379579,1.698838,2.944690,2.247099,0.233153,-0.286142,-0.433915

In [12]:
dfmn1 = tst_df.groupby('ID').mean()
dfst1 = tst_df.groupby('ID').std()
dfmi1 = tst_df.groupby('ID').min()
dfma1 = tst_df.groupby('ID').max()
dfsk1 = tst_df.groupby('ID').skew() #왜도

In [13]:
tst_df = pd.concat([dfmn1,dfst1,dfmi1,dfma1,dfsk1],axis=1)
tst_df

,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C,sensor_A,sensor_B,sensor_C
ID,,,,,,,,,,,,,,,
8960.0,0.071084,-0.069369,-0.075136,1.064367,0.969900,1.059073,-2.143235,-2.285735,-2.239960,2.293006,2.914095,2.300860,-0.011280,0.202557,0.272653
8961.0,0.031851,0.021130,0.050976,1.084123,0.957770,1.064134,-2.269555,-2.268553,-2.401180,2.335526,3.197478,2.883419,-0.066405,0.052269,-0.081803
8962.0,-0.094004,0.021193,-0.049337,0.991206,0.910789,0.958661,-1.593307,-2.397788,-2.287381,1.981793,3.172244,2.038992,0.372964,0.173876,-0.348163
8963.0,-0.032039,0.040759,0.008774,1.122295,1.064096,0.919389,-2.899868,-4.473934,-1.777084,2.076592,2.085305,2.319964,-0.299933,-0.945332,0.637122
8964.0,-0.027369,0.052631,-0.079393,0.993172,1.039673,1.173177,-1.569395,-3.011533,-2.589172,1.882426,2.558500,2.539626,0.197350,-0.409999,0.109854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11195.0,0.091232,0.004996,0.014900,0.894748,0.916014,1.123445,-2.603755,-2.872310,-2.339551,2.058825,1.964740,2.415459,0.087783,-0.381140,0.034210
11196.0,0.053182,0.040998,0.031626,1.042445,0.709999,0.980311,-1.629263,-2.096825,-3.277595,2.154216,2.420189,1.994715,0.414141,0.080736,-1.032300
11197.0,0.059639,0.030932,0.021782,1.076124,0.823452,1.034795,-1.731937,-1.673851,-3.317743,2.202882,2.444603,2.202676,0.373674,0.179471,-0.730592
11198.0,-0.001770,0.007180,0.066414,0.925331,1.052979,0.996140,-2.118622,-3.248447,-2.529880,2.115083,2.354236,2.457832,-0.120664,-0.596103,0.289504
11199.0,0.048410,-0.008800,-0.021946,0.994392,0.969629,0.929404,-1.920219,-3.026202,-1.646191,2.063344,3.020111,2.037872,0.039837,-0.328653,0.190446

In [14]:
trn_df.shape

(8960, 15)

In [15]:
tst_df.shape

(2240, 15)

In [16]:
# trn_df.kurt() #첨도는 groupby 안에 없음 -> 못만들 듯

In [17]:
axis = 0

In [18]:
# k = []
# for i in range(8960):
#     for j in range(131):
#         for l in trn_df[trn_df['ID'] == j]:
#             k.append(np.mean(trn_df['sensor_A']))
# print(k)

In [19]:
# k = []
# for i in range(8960):
#     while (k[-1] == 131*i):
#         k.append(np.mean(trn_df['sensor_A']))
# print(k)

In [20]:
# n = 131
# result = [trn_df[i * n:(i + 1) * n] for i in range((len(trn_df) + n - 1) // n )]

In [21]:
# list_df = pd.DataFrame(result)

In [22]:
# trn_df = trn_df.drop(['ID'],axis=1)
# tst_df = tst_df.drop(['ID'],axis=1)
# lab_df = lab_df.drop(['ID'],axis=1)

In [23]:
scaler = MinMaxScaler()

In [24]:
file_path = scaler.fit(trn_df)
print(scaler.n_samples_seen_, scaler.data_min_, scaler.data_max_, scaler.feature_range)

8960 [-0.28061444 -0.14633584 -0.25381971  0.03324626  0.50390908  0.66540985
 -3.6195614  -5.8968425  -4.385735    0.0532403   1.0929492   1.1240944
 -0.8538441  -1.31450508 -1.3085503 ] [ 0.35344639  0.1756892   0.25512256  1.31118759  1.79439159  1.72837714
 -0.02603093 -1.1876738  -1.1491022   3.6801076   4.599791    4.074743
  1.00379776  0.91075435  1.02329143] (0, 1)

In [25]:
# df_values = trn_df.values
# datalist = []
# datalist.append(df_values)
# data_array = np.array(trn_df)
# data_reshape = data_array.reshape(8960, 131*3)

In [26]:
# df_values1 = tst_df.values
# datalist1 = []
# datalist1.append(df_values1)
# data_array1 = np.array(tst_df)
# data_reshape1 = data_array1.reshape(2240, 131*3)

In [27]:
# trn_df = data_reshape
# tst_df = data_reshape1

In [28]:
X_trn = trn_df
Y_trn = lab_df

X_tst = tst_df

In [29]:
X_trn.shape, Y_trn.shape

((8960, 15), (8960,))

In [30]:
X_tst.shape

(2240, 15)

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, train_test_split

In [32]:
model = RandomForestClassifier(n_estimators=200)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X_trn, Y_trn, test_size=0.1, random_state=100)

In [34]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(8064, 15) (896, 15) (8064,) (896,)

In [ ]:
model.fit(X_train, y_train)

In [20]:
y_predict = model.predict(X_test)

In [21]:
# mean_squared_error(y_test, y_predict, squared=False)

In [22]:
acc = accuracy_score(y_test, y_predict)
print('accuracy_score : ',acc)

accuracy_score :  0.9832589285714286

In [23]:
test_prediction = model.predict(X_tst)

In [24]:
sample = os.path.join(datapath, 'answer_sample.csv')

In [25]:
sample_submission = pd.read_csv(sample)

In [26]:
sample_submission

         ID  type
0      8960     0
1      8961     0
2      8962     0
3      8963     0
4      8964     0
...     ...   ...
2235  11195     0
2236  11196     0
2237  11197     0
2238  11198     0
2239  11199     0

[2240 rows x 2 columns]

In [27]:
sample_submission['type'] = test_prediction

In [28]:
sample_submission.to_csv('E:/중급/test_submission4.csv', index=False)

In [29]:
f1_score(y_true, y_pred, average='macro')

NameError: name 'f1_score' is not defined